---
- name: set up sources
  hosts: all
  tags: casks
  sudo: false
  tasks:
  - name: get homebrew taps setup
    homebrew_tap: tap={{ item }} state=present
    always_run: yes
    with_items:
      - caskroom/cask
      - homebrew/binary

  - name: get homebrew sources setup
    homebrew: name=brew-cask  state=present
    always_run: yes

- name: essential tools for shell environment
  hosts: all
  tags: essential
  sudo: false
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - gh #formerly hub
      - ssh-copy-id
      - imagemagick

  - name: install essential shell casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - xquartz


- name: Programming languages and environment platforms
  hosts: all
  tasks:
    - include: tasks/go.yml      tags=go
      vars:
        gopath: ~/src/go

    - include: tasks/ruby.yml    tags=ruby
      vars:
        global_ruby: 2.2.0
        default_gems:
          - bundler
        rubies:
          - 1.9.3-p551
          - 2.1.5
          - 2.2.0
          
- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # webdevs need all the webs (except opera lol)
      - google-chrome
      # - firefox
      # text editors i hate the least
      - atom
      - macvim
      # - mou
      # virtual machine management
      # - vmware-fusion
      # TODO: not currently doing any VM based development, reenable below when
      # doing so.
      # - vagrant
      - virtualbox
      # other dev tools
      - iterm2
      - dash
      - github
      # non-dev stuff for general productivity
      - caffeine
      - cloud
      - daisydisk
      - dropbox
      - flux
      - sizeup
      # bloated business shit
      - skype
      # - evernote #TODO possible to get rid of this bloated POS?
      # non-dev stuff for general unproductivity
      # - steam
      # - spotify
      - transmission
      - vlc

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # dev tools
      - ack
      - jq
      - gist
      # heroku style development
      - heroku-toolbelt
      - forego
      # networking tools
      - curl
      - wget
      - speedtest_cli
      - httpie
      # security tools
      - gnupg
      - nmap
      - pwgen
      # media related tools
      - imagesnap
      - pianobar
      - ffmpeg
