---
- name: set up sources
  hosts: all
  tags: casks
  sudo: false
  tasks:
  - name: get homebrew taps setup
    homebrew_tap: tap={{ item }} state=present
    always_run: yes
    with_items:
      - caskroom/cask
      - homebrew/binary

  - name: get homebrew sources setup
    homebrew: name=brew-cask  state=present
    always_run: yes

- name: essential tools for shell environment
  hosts: all
  tags: essential
  sudo: false
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - hub
      - scmpuff
      - ssh-copy-id
      - imagemagick

  - name: remove legacy shell brews
    homebrew: name={{ item }} state=absent
    with_items:
      - gh #gh is now hub

  - name: install essential shell casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - xquartz


- name: Programming languages and environment platforms
  hosts: all
  tasks:
    - include: tasks/docker.yml  tags=docker,xtra
    - include: tasks/elixir.yml  tags=elixir
    - include: tasks/haskell.yml tags=haskell,xtra
    - include: tasks/rust.yml    tags=rust,xtra
    - include: tasks/go.yml      tags=go
      vars:
        gopath: ~/src/go

    - include: tasks/node.yml    tags=node
      vars:
        global_modules:
          - coffee-script
          - bower

    - include: tasks/ruby.yml    tags=ruby
      vars:
        global_ruby: 2.3.1
        default_gems:
          - bundler
        rubies:
          # - 1.9.3-p551
          # - 2.2.5
          - 2.3.1
        legacy_rubies:
          - 2.1.5
          - 2.2.0
          - 2.2.1
          - 2.2.2
          - 2.2.3
          - 2.2.4
          - 2.3.0

- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # webdevs need all the webs (except opera lol)
      # - google-chrome
      # - firefox
      # text editors i hate the least
      # - atom
      - macvim
      # - mou
      # virtual machines
      # - vmware-fusion
      # other dev tools
      # - dash
      - github-desktop
      # non-dev stuff for general productivity
      - caffeine
      # - cloud
      # - daisydisk
      - dropbox
      - flux
      # non-dev stuff for general unproductivity
      # - steam
      # - transmission
      # - vlc

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # dev tools
      - ack
      - jq
      - gist
      # text editor assistance
      - ctags
      - shellcheck
      # heroku style development
      - heroku-toolbelt
      - forego
      # networking tools
      - curl
      - wget
      - speedtest_cli
      # security tools
      - keybase
      - gnupg
      - nmap
      - pwgen
      # media related tools
      - pianobar
      - ffmpeg