---
- name: install Go platform
  homebrew: name=go state=present

- name: install tools needed for `go get` to function as expected
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - hg
    - bzr

- name: install tools for less sucky Go dependency management
  homebrew: name={{ item }} state=present
  with_items:
    - godep
    - glide

- name: install additional Go tools
  command: go get {{ item }}
  environment:
    GOPATH:  "{{ gopath | expanduser }}"
  args:
    creates: "{{ gopath | expanduser }}/src/{{ item }}/"
  with_items:
    - golang.org/x/tools/cmd/godoc
    - golang.org/x/tools/cmd/vet
    - golang.org/x/tools/cmd/cover
    - github.com/kisielk/errcheck
